### ISSUE TITLE
search_api_solr shows "Outdated solr configuration"

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev-drupal9-solr#15]
Today I tried to setup a Solr server.
After following the instructions and clicking save, I recieved 2 messages:

- "The server was successfully saved."
- "You are using outdated Solr configuration set. Please follow the instructions described in the [README.md](https://solr-d10-demo.ddev.site/modules/contrib/search_api_solr/README.md) file for setting up Solr."

![outdated_config](https://user-images.githubusercontent.com/7234392/215934168-f77ed284-6836-4546-b456-93ae57e61470.png)

It states it can connect OK is the view table in Drupal 10. And the configured version and detected version appear to match:

|  |  |
| --- | --- |
| Server Connection | The Solr server could be reached. |
| Core Connection | The Solr core could be accessed (latency: 10.037945343018 ms).|
|Configured Solr Version |8.11.2 |
|Detected Solr Version |8.11.2 |

However, I am unfamiliar with Solr so not really sure if there are any "issues". 
We may need to update the configuration or, perhaps, add a note on the addon page to "ignore the warning".

## Test

1.. Follow installation guide.
2. Click "save"
3. Check messages.

DDEV: `1.24.1`
Drupal: `10.0.2`

**Comment by tyler36** [comment]
Also appears when install on Drupal `9.5.1`

**Comment by rfay** [comment]
This complaint is @mkalkbrenner, the maintainer of search_api_solr, telling us that he doesn't want us to use the "Standard" solr connector any more, he wants us to use Solr Cloud. 

Details in 
* https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/solr
* https://github.com/drud/ddev-contrib/pull/195

But this add-on is specifically intended to use the "Standard" solr connector. I would dearly love to see something more approved by @mkalkbrenner but he hasn't responded in the problem issues. I think we can do it though. I'm just not good enough with solr to want to maintain something even more complex than this is. 

However, I'm sure that with the two links above we could get solr cloud going in a new add-on.

**Comment by zuuperman** [comment]
The complaint is not related with Solr cloud. If you verify the code, it checks the version number in config.

Currently our version number is drupal-4.2.6-solr. While the SEARCH_API_SOLR_MIN_SCHEMA_VERSION const is currently set to 4.2.8.

**Comment by rfay** [comment]
How should one work around this then @zuuperman ?  It doesn't seem to be anything but a warning message.

**Comment by gitressa** [comment]
I have created [Error message - You are using outdated Solr configuration set](https://www.drupal.org/project/search_api_solr/issues/3366092).

**Comment by gitressa** [comment]
I got it working by updating the Solr config in DDEV, see [this comment](https://www.drupal.org/project/search_api_solr/issues/3366092#comment-15099906) in the issue above for details.

If someone else can confirm that this method fixes the issue, I can add this step to the ddev-drupal9-solr README.

Thanks for your comment @zuuperman. I recalled it after I did a diff between the config files, and saw that the version in some config files is created with Search API Solr version 4.2.6. Since Search API Solr version 4.2.10 is the current release, it is the version included in newly created config files:
```
-<schema name="drupal-4.2.6-solr-8.x-0" version="1.6">
+<schema name="drupal-4.2.10-solr-8.x-0" version="1.6">
```

I have created https://github.com/mkalkbrenner/search_api_solr/pull/91 to hopefully make it clearer to the user what the problem and solution is.

**Comment by rfay** [comment]
Yay, thanks for your work on this. If you can improve the docs here that will be very welcome.

**Comment by gitressa** [comment]
Sure! I have created #27.

**Comment by tyler36** [comment]
Is this still valid?

**Comment by mkalkbrenner** [comment]
This is not related to a the ddev module. It is drupal.
