### ISSUE TITLE
data not persistent

### ISSUE THREAD

**Issue by 1xfsanchez** [ddev/ddev-drupal9-solr#19]
Hi,

I've been using this template and I found that when running `ddev restart` the solr data get cleared.

After digging, I found that the volume path used for is wrong, and the real data is saved in other location.

**Comment by 1xfsanchez** [comment]
I created this PR: https://github.com/ddev/ddev-drupal9-solr/pull/20

**Comment by rfay** [comment]
This issue appears to be obsolete. Closing.
