### ISSUE TITLE
How to delete the "dev" Solr core created on installation

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev-drupal9-solr#28]
Just go to this URL in your browser, replace `<PROJECT>` with your project name:

`http://<PROJECT>.ddev.site:8983/solr/admin/cores?action=UNLOAD&core=dev&deleteInstanceDir=true`

**Comment by gitressa** [comment]
This is mostly just to document it, so closing.

**Comment by rfay** [comment]
Do you think it should be added to docs? Why did you want to delete it? You can also delete the related docker volume, and `ddev delete` will also delete it.

**Comment by gitressa** [comment]
Thanks for sharing extra methods of removing it @rfay. `ddev delete` I can understand, but how would I delete the related docker volume you mention? 

I guess it could be added to the README ... I deleted it because I prefer my development configuration to match production the closest, so I set the Solr core name to that, and deleted `dev` Solr core to clean things up.

Could the Solr core pull its name automagically from the folder name, like the DDEV configuration does? That would be the ideal solution for me.

**Comment by rfay** [comment]
I'd rather have you move on to the up-and-coming https://github.com/mkalkbrenner/ddev-solr - would you be willing to go test that one? It will soon be promoted... and with that one you don't have the magic "dev" core setup and such.

**Comment by rfay** [comment]
BTW, you could easily have deleted the core using the web UI couldn't you?

**Comment by gitressa** [comment]
I am not sure how to move the set up to production (like I wrote here: [A missing piece in the puzzle ...](https://github.com/ddev/ddev-contrib/issues/221#issuecomment-1591669495)) so I'll probably stick to this for now. It would be a waste of time to set it up, and not be able to use it.

I don' know if it's possible via web UI?

**Comment by rfay** [comment]
All you have to do is open the solr UI (port 8983, shown by `ddev describe`) to try it out.

**Comment by gitressa** [comment]
Ah yes, there's an "Unload" button under "Core Admin" at `http://PROJNAME.ddev.site:8983/solr/#/~cores/dev` which removes it. I had already removed `dev` so I tried removing my `customname` core. But now it wouldn't recreate after a `ddev restart`. I had to `ddev delete` to restore it. There are many ways to skin this goat :)

**Comment by gitressa** [comment]
I created a PR which adds a line about this to the README.

**Comment by rfay** [comment]
Thanks, and please don't forget to check out https://github.com/ddev/ddev-drupal9-solr/issues/28#issuecomment-1608049911

https://github.com/mkalkbrenner/ddev-solr

**Comment by gitressa** [comment]
Thanks and yes, I am following the repo now. I hope deployment to server steps will be added, otherwise it's not that useful IMO.

**Comment by rfay** [comment]
Please open an issue in https://github.com/mkalkbrenner/ddev-solr with your request. I don't think people typically deploy local solr stuff to server.

**Comment by gitressa** [comment]
Sorry if I didn't word it precisely enough.

The classic way of installing Solr on a server, creating a core, moving the config in place, etc. is very well documented in the README under <a href="https://git.drupalcode.org/project/search_api_solr#setting-up-solr-single-core-the-classic-way">Setting up Solr (single core) - the classic way</a>.</p>

I can follow these steps and successfully get a single core Solr Classic instance running on a production server.

My problem is that I don't know how to similarly set up Solr Cloud on a server.

There is an existing issue drupal.org issue [Add more details on how to set up Solr Cloud on a server in README](https://www.drupal.org/project/search_api_solr/issues/3365751) which I have updated with links to the new https://github.com/mkalkbrenner/ddev-solr repo as well as updated the Issue Summary, since I now see that there actually are sections about setting up Solr Cloud.

But they are very basic, and could use some more detail, for them to be useful.

**Comment by gitressa** [comment]
Just at tip to myself and others, if you are using the new Solr Cloud solution and need to delete a core and also a collection, you can do it via the GUI, like "dev" core from `http://<projectname>.ddev.site:8983/solr/#/~cores/dev` by clicking "Unload".

... or delete both collections and cores via these URLs:

Delete a collection called `dev`:
https://mysite.ddev.site:8943/solr/admin/collections?action=DELETE&name=dev

Delete a core called `dev_shard1_replica_n1`:
https://mysite.ddev.site:8943/solr/admin/cores?action=UNLOAD&core=dev_shard1_replica_n1&deleteInstanceDir=true

Now, you can create a fresh set Core and Collection, which uses the Solr server settings from Drupal:
`drush search-api-solr:upload-configset --numShards=1 solr_server`

EDIT: I added it here as well: https://www.drupal.org/docs/8/modules/search-api-solr/search-api-solr-howtos/how-to-delete-solr-core-and-collection-or-all-documents
