### ISSUE TITLE
Use a security.json file

### ISSUE THREAD

**Issue by clemorphy** [ddev/ddev-drupal9-solr#35]
Hi

Is there a simple way to use a security.json file?
By "simple" I mean as easy as putting the core config files in the /conf directory.
I have created a .ddev/solr/security.json file and restarted my project, but it seems that it's not the right way.

Thanx

**Comment by rfay** [comment]
I think the easiest way would be to add a `build` section to a docker-compose.solr_extra.yaml and add the security.json.

Can you say a little about why you want to add it and what a security.json is?

Also, please note that [ddev/ddev-solr](https://github.com/ddev/ddev-solr) is the most likely future of this project, so if you're not already using this, please do check in over there.

**Comment by clemorphy** [comment]
A security.json file is what Solr is reading to setup authentication and authorization policies : https://solr.apache.org/guide/8_1/authentication-and-authorization-plugins.html

Thanks for pointing [ddev/ddev-solr](https://github.com/ddev/ddev-solr), I wasn't aware of this project.

**Comment by rfay** [comment]
(I don't know much about solr) so why would you need security.json in a local development environment?

If you wannt this issue transferred to ddev/solr I can move it there if you end up using that.

The maintainer of ddev/solr is extremely knowledgable about solr and may want to add a security.json in general to the project.

**Comment by clemorphy** [comment]
I wanted to test securing solr on my local environment before deploying this to our remote dev environment. But in the end It looks that the second option is gonna be easier for me. I'll check the ddev/solr project later if I find some time.
Thanks.

**Comment by rfay** [comment]
I happened to notice today in our add-on training that there is a [security.json](https://github.com/ddev/ddev-solr/blob/main/solr/security.json) in the ddev-solr add-on, and you could override it, but you'd have to remove the #ddev-generated line from it.
