### ISSUE TITLE
Support for Solr 9?

### ISSUE THREAD

**Issue by Defcon0** [ddev/ddev-drupal9-solr#43]
Hello,

since https://www.drupal.org/project/search_api_solr supports Solr 9 are there any plans to release a version of this image for supporting the latest version?

Thanks!

Bye Defcon0

**Comment by rfay** [comment]
Hi @Defcon0 

1. The preferred add-on is https://github.com/ddev/ddev-solr, maintained by the maintainer of search_api_solr.
2. To override the solr version you can add a `docker-compose.solr_extras.yaml` with something like this (untested, but standard procedure):
```
services:
  solr:
    image: solr:9
```
