### ISSUE TITLE
Remove Paragraph Clean module

### ISSUE THREAD

**Issue by pau1m** [ddev/ddev-drupal9-solr#5]
Why? 

Documentation states

* Not compatible with revisions. Creating node / entity revisions with varying paragraph relations will have _adverse_ _consequences_.
* if you're re-using paragraphs among different entities, then don't install this module.

https://www.drupal.org/project/paragraphs_clean

**Comment by rfay** [comment]
Hmm, this DDEV add-on doesn't install any modules... Did you file this in the wrong place?

**Comment by pau1m** [comment]
yup, wrong repo. Sorry.
